import Order from "../models/order.model";
import applyService from "./apply.service";
import { calculateSubtotal } from "../utils/order.utils";
import Voucher, { IVoucher } from "../models/voucher.model";
import Promotion, { IPromotion } from "../models/promotion.model";

class OrderService {
  async createOrder(input: any) {
    const { userId, items, code } = input;

    const subtotal = calculateSubtotal(items);
    let discount = 0;
    let total = subtotal;
    let appliedCodes: any[] = [];

    let voucherId = null;
    let promotionId = null;

    if (code) {
      const result = await applyService.applyCode({ code, items });
      discount = result.discount;
      total = result.total;

      // Fetch the object for reference ID
      const ref: IVoucher | IPromotion | null =
        ((await Voucher.findOne({ code: code.toUpperCase() })) as IVoucher) ??
        ((await Promotion.findOne({ code: code.toUpperCase() })) as IPromotion);

      if (ref) {
        if ("autoGenerated" in ref) voucherId = ref._id;
        else promotionId = ref._id;
      }

      appliedCodes.push({
        type: voucherId ? "voucher" : "promotion",
        code: code.toUpperCase(),
        appliedAmount: discount,
        voucherId,
        promotionId,
      });
    }

    const order = await Order.create({
      userId,
      items,
      subtotal,
      appliedCodes,
      total,
    });

    return order;
  }

  async getOrder(id: string) {
    return Order.findById(id);
  }

  async listOrders() {
    return Order.find().sort({ createdAt: -1 });
  }
}

export default new OrderService();
