import Voucher, { IVoucher } from "../models/voucher.model";

class VoucherService {
  async create(data: Partial<IVoucher>): Promise<IVoucher> {
    if (!data.code) {
      data.autoGenerated = true;
      data.code = this.generateCode();
    }

    data.code = data.code.toUpperCase();

    return Voucher.create(data);
  }

  async getAll(): Promise<IVoucher[]> {
    return Voucher.find({ isActive: true }).sort({ createdAt: -1 });
  }

  async getByCode(code: string): Promise<IVoucher | null> {
    return Voucher.findOne({
      code: code.toUpperCase(),
      isActive: true,
    });
  }

  async update(
    code: string,
    updates: Partial<IVoucher>
  ): Promise<IVoucher | null> {
    return Voucher.findOneAndUpdate({ code: code.toUpperCase() }, updates, {
      new: true,
    });
  }

  /** Soft delete mark isActive: false */
  async delete(code: string): Promise<IVoucher | null> {
    return Voucher.findOneAndUpdate(
      { code: code.toUpperCase() },
      { isActive: false },
      { new: true }
    );
  }

  private generateCode(): string {
    return "VOUCH-" + Math.random().toString(36).substring(2, 10).toUpperCase();
  }
}

export default new VoucherService();
