import { z } from "zod";
import { DiscountType } from "../models/enums";

export const createVoucherSchema = z.object({
  code: z.string().optional(), // can be auto-generated
  autoGenerated: z.boolean().optional(),

  discountType: z.enum(Object.values(DiscountType)),
  discountValue: z.number().positive(),

  maxDiscountAmount: z.number().positive().optional(),
  expiresAt: z.coerce.date(), // will convert to Date in controller

  totalUsesAllowed: z.number().int().positive().optional(),
  minOrderValue: z.number().positive().optional(),

  applicableProductIds: z.array(z.string()).optional(),
  applicableCategoryIds: z.array(z.string()).optional(),
  metadata: z.record(z.string(), z.any()).optional(),
});

export const updateVoucherSchema = createVoucherSchema.partial().extend({
  isActive: z.boolean().optional(),
});
