import mongoose, { Document, Schema } from "mongoose";
import { DiscountType } from "./enums";

export interface IVoucher extends Document {
  code: string;
  autoGenerated: boolean;
  discountType: DiscountType;
  discountValue: number;
  maxDiscountAmount?: number;
  expiresAt: Date;
  totalUsesAllowed?: number;
  usesCount: number;
  minOrderValue?: number;
  applicableProductIds?: string[];
  applicableCategoryIds?: string[];
  metadata?: Record<string, any>;
  isActive: boolean;
}

const VoucherSchema = new Schema<IVoucher>(
  {
    code: { type: String, unique: true, required: true },
    autoGenerated: { type: Boolean, default: false },

    discountType: {
      type: String,
      enum: Object.values(DiscountType),
      required: true,
    },
    discountValue: { type: Number, required: true },
    maxDiscountAmount: { type: Number },

    expiresAt: { type: Date, required: true },
    totalUsesAllowed: { type: Number },
    usesCount: { type: Number, default: 0 },

    minOrderValue: { type: Number },

    applicableProductIds: [{ type: String }],
    applicableCategoryIds: [{ type: String }],

    metadata: { type: Object },
    isActive: { type: Boolean, default: true },
  },
  { timestamps: true }
);

VoucherSchema.index({ expiresAt: 1 });
VoucherSchema.index({ isActive: 1 });

export default mongoose.model<IVoucher>("Voucher", VoucherSchema);
